server:
  port: ${SERVER_PORT}
  servlet:
    session:
      timeout: 60m

logging:
  level:
    org.springframework.web.cors: DEBUG

okta:
  oauth2:
    issuer: ***REMOVED***
    client-id: ***REMOVED***
    client-secret: ***REMOVED***
