server:
  port : ${SERVER_PORT}
  servlet:
    session:
      timeout: 60m

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
#          spotify:
#            client-id: ${CLIENT_ID}
#            client-secret: ${CLIENT_SECRET}
#            redirect-uri: ${REDIRECT_URI}
#            provider: spotify
#            scope: user-read-private, user-read-email, user-library-read
#            authorization-grant-type: authorization_code
#        provider:
#          spotify:
#            authorization-uri: https://accounts.spotify.com/authorize
#            token-uri: https://accounts.spotify.com/api/token
#            user-info-uri: https://api.spotify.com/v1/me
#            user-name-attribute: id
