server:
  port: ${SERVER_PORT}
  servlet:
    session:
      timeout: 60m

logging:
  level:
    org.springframework.web.cors: DEBUG

okta:
  oauth2:
    issuer: https://dev-wgrfncmy5tahnvay.us.auth0.com/
    client-id: ol7AX5wMtZ7MdEFgdOEsjd8iJAu75udo
    client-secret: m3mvY5MGI1rkNSSGNhkQDpAwn9V_Jre6-XzvCNca_tm_wN-bY8IfCHgMBEZ0kPZG
